Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>ReceiversName</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Invoice__c/fields/InvoiceNo__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNo__c</fullName>
    <label>InvoiceNo</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Public Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Profile__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret key</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/classes/InvoiceDataAccess.cls
public class InvoiceDataAccess {
   public static  Profile__c getProfile() {
        return [SELECT Name, Secret_Key__c FROM Profile__c LIMIT 1];
     }
        
   public static String getPublicKey() {
        Profile__c credentials= getProfile();
        String publicKeys = credentials.Name; 
        return publicKeys;
      }
  
    public static Invoice__c invoiceNumber(String invoiceId) {
        List<Invoice__c> invoices = [SELECT Id, InvoiceNo__c FROM Invoice__c WHERE Id = :invoiceId LIMIT 1];

        if (invoices != null && !invoices.isEmpty()) {
            return invoices[0];
        } else {
            return null;
        }
    }
}