Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/Payments__c.object-meta.xml
<CustomObject>
    <label>Payments</label>
    <nameField>
        <label>Payload Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NG</fullName>
                <default>true</default>
                <label>NG</label>
            </value>
            <value>
                <fullName>Ghana</fullName>
                <isActive>false</isActive>
                <label>Ghana</label>
            </value>
            <value>
                <fullName>India</fullName>
                <isActive>false</isActive>
                <label>India</label>
            </value>
            <value>
                <fullName>Kenya</fullName>
                <isActive>false</isActive>
                <label>Kenya</label>
            </value>
            <value>
                <fullName>Tanzania</fullName>
                <isActive>false</isActive>
                <label>Tanzania</label>
            </value>
            <value>
                <fullName>United States</fullName>
                <isActive>false</isActive>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Payment_Link_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Id__c</fullName>
    <label>Payment Link Id</label>
    <type>Url</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Payment_Link_Reference__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Reference__c</fullName>
    <label>Payment Link Reference</label>
    <type>Url</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Virtual_Account__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Virtual Account</label>
    <referenceTo>Virtual_Account__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/Virtual_Account__c.object-meta.xml
<CustomObject>
    <label>Virtual Account</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NG</fullName>
                <default>true</default>
                <label>NG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/classes/SeerbitPaymentDetailsController.cls
public with sharing class SeerbitPaymentDetailsController {
    @AuraEnabled(cacheable=true)
    public static List<Payments__c> getPayments(String virtualAccountId) {
        return [SELECT Id, Amount_Paid__c, Country__c, Customer_Email__c, Customer_Name__c, Payment_Date__c,
                 Payment_Link_Id__c, Payment_Link_Reference__c, Payment_Reference__c, Payment_Status__c, Reason__c
                 FROM Payments__c
                 WHERE Virtual_Account__c = :virtualAccountId];
    }
}