Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/Payments__c.object-meta.xml
<CustomObject>
    <label>Payments</label>
    <nameField>
        <label>Payload Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NG</fullName>
                <default>true</default>
                <label>NG</label>
            </value>
            <value>
                <fullName>Ghana</fullName>
                <isActive>false</isActive>
                <label>Ghana</label>
            </value>
            <value>
                <fullName>India</fullName>
                <isActive>false</isActive>
                <label>India</label>
            </value>
            <value>
                <fullName>Kenya</fullName>
                <isActive>false</isActive>
                <label>Kenya</label>
            </value>
            <value>
                <fullName>Tanzania</fullName>
                <isActive>false</isActive>
                <label>Tanzania</label>
            </value>
            <value>
                <fullName>United States</fullName>
                <isActive>false</isActive>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>NGN</fullName>
                <default>true</default>
                <label>NGN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Virtual_Account__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Virtual Account</label>
    <referenceTo>Virtual_Account__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Public Key</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Profile__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country/Region Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NG</fullName>
                <default>true</default>
                <label>NG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Profile__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NGN</fullName>
                <default>true</default>
                <label>NGN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Profile__c/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret key</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/Virtual_Account__c.object-meta.xml
<CustomObject>
    <label>Virtual Account</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <label>Bank Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NG</fullName>
                <default>true</default>
                <label>NG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NGN</fullName>
                <default>true</default>
                <label>NGN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/WalletId__c.field-meta.xml
<CustomField>
    <fullName>WalletId__c</fullName>
    <label>Wallet id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/WalletName__c.field-meta.xml
<CustomField>
    <fullName>WalletName__c</fullName>
    <label>Wallet Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

Salesforce_SeerBIt_PlugIn/force-app/main/default/classes/VirtualAccountDataAccess.cls
public class VirtualAccountDataAccess {
    
    public static Id getVirtualAccountLookupId(String accountNumber) {
        Virtual_Account__c virtualAccount = [SELECT Id FROM Virtual_Account__c WHERE AccountNumber__c = :accountNumber LIMIT 1];
        return virtualAccount != null ? virtualAccount.Id : null;
    }
    
    /* @AuraEnabled(cacheable=true)
        public static Virtual_Account__c getVirtualAccountById(Id virtualAccountId) {
        return [SELECT Id,Name, Email__c, Reference__c, BankName__c, WalletName__c,  WalletId__c, AccountNumber__c, Country__c, Currency__c FROM Virtual_Account__c where Id=:virtualAccountId LIMIT 1];
        }*/

    @AuraEnabled
    public static Virtual_Account__c getVirtualAccount(String recordId){
        return [SELECT Id,Name, Email__c, Reference__c, BankName__c, WalletName__c,  WalletId__c, AccountNumber__c, Country__c, Currency__c FROM Virtual_Account__c where Id=:recordId LIMIT 1];
    }
    
    public static Virtual_Account__c getVirtualAccounts(String referenceId){
        return [SELECT Id,  Name, Email__c, Reference__c, BankName__c, WalletName__c, WalletId__c, AccountNumber__c, Country__c, Currency__c FROM Virtual_Account__c where Reference__c=:referenceId LIMIT 1];
    }
    
    @AuraEnabled
    public static Map<String, Object> deleteVirtualAccount(String virtualAccountId) {
        Map<String, Object> responseObj = new Map<String, Object>();
        try {
                Virtual_Account__c virtualAccObj = [SELECT Id, Name, Email__c, Reference__c, BankName__c, WalletName__c, WalletId__c, AccountNumber__c, Country__c, Currency__c FROM Virtual_Account__c WHERE Id = :virtualAccountId LIMIT 1];
    
                // Query related payments based on the Virtual Account Id
                List<Payments__c> relatedPayments = [SELECT Id FROM Payments__c WHERE Virtual_Account__c = :virtualAccObj.Id];
                delete relatedPayments;
                delete virtualAccObj;
                responseObj.put('success', true);
            } catch (Exception e) {
                    responseObj.put('success', false);
                    responseObj.put('errors', new List<String>{'An error occurred while deleting the Virtual Account.'});
                }
        return responseObj;
    }
    
    /*@AuraEnabled
    public static List<Payments__c> getSortedPayments(String virtualAccountId) {
        return [SELECT Id, Name, Amount_Paid__c, Payment_Date__c FROM Payments__c WHERE Virtual_Account__c = :virtualAccountId ORDER BY Payment_Date__c DESC];
    }*/
    
    public  static Profile__c getProfile() {
        return [SELECT Name, Secret_Key__c FROM Profile__c LIMIT 1];
    }
    
    
    public static String getPublicKey() {
        Profile__c credentials=[SELECT  Name,Secret_Key__c FROM Profile__c LIMIT 1];
        String publicKeys = credentials.Name; 
        return publicKeys;
    }
    
    @AuraEnabled
    public static void updateVirtualAccountAura(String virtualAccountId) {
        try {
            Virtual_Account__c virtualAccountObj = getVirtualAccount(virtualAccountId);
            VirtualAccountService.processUpdates(virtualAccountObj);
        } catch (Exception e) {
              throw new HandleCustomException('Error during updateVirtualAccountAura: ' + e.getMessage() + ' Line Number:' + e.getLineNumber(), e);

        } 
    }
}