Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/Payments__c.object-meta.xml
<CustomObject>
    <label>Payments</label>
    <nameField>
        <label>Payload Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NG</fullName>
                <default>true</default>
                <label>NG</label>
            </value>
            <value>
                <fullName>Ghana</fullName>
                <isActive>false</isActive>
                <label>Ghana</label>
            </value>
            <value>
                <fullName>India</fullName>
                <isActive>false</isActive>
                <label>India</label>
            </value>
            <value>
                <fullName>Kenya</fullName>
                <isActive>false</isActive>
                <label>Kenya</label>
            </value>
            <value>
                <fullName>Tanzania</fullName>
                <isActive>false</isActive>
                <label>Tanzania</label>
            </value>
            <value>
                <fullName>United States</fullName>
                <isActive>false</isActive>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>NGN</fullName>
                <default>true</default>
                <label>NGN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Payments__c/fields/Virtual_Account__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Virtual Account</label>
    <referenceTo>Virtual_Account__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/VA_Notificaton__c.object-meta.xml
<CustomObject>
    <label>VA Notificaton</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VA Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NG</fullName>
                <default>true</default>
                <label>NG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Credit_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Credit_Account_Name__c</fullName>
    <label>Credit Account Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Credit_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Credit_Account_Number__c</fullName>
    <label>Credit Account Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NGN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/External_Reference__c.field-meta.xml
<CustomField>
    <fullName>External_Reference__c</fullName>
    <label>External Reference</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Gateway_Code__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Code__c</fullName>
    <label>Gateway Code</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Gateway_Message__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Message__c</fullName>
    <label>Gateway Message</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/InternalRef__c.field-meta.xml
<CustomField>
    <fullName>InternalRef__c</fullName>
    <label>InternalRef</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Narration__c.field-meta.xml
<CustomField>
    <fullName>Narration__c</fullName>
    <label>Narration</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Originator_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Originator_Account_Number__c</fullName>
    <label>Originator Account Number</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Originator_Name__c.field-meta.xml
<CustomField>
    <fullName>Originator_Name__c</fullName>
    <label>Originator Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Public_Key__c</fullName>
    <label>Public Key</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/VA_Notificaton__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/Virtual_Account__c.object-meta.xml
<CustomObject>
    <label>Virtual Account</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Virtual Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NG</fullName>
                <default>true</default>
                <label>NG</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NGN</fullName>
                <default>true</default>
                <label>NGN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Salesforce_SeerBIt_PlugIn/force-app/main/default/objects/Virtual_Account__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

Salesforce_SeerBIt_PlugIn/force-app/main/default/classes/VANotification.cls
@RestResource(urlMapping='/vanotification/v1/*')
global class VANotification {

    @AuraEnabled
    @HttpPost
    global static String handleNotification() {
        try {
            String requestBody = RestContext.request.requestBody.toString();
            NotificationRequest req = (NotificationRequest) JSON.deserialize(requestBody, NotificationRequest.class);

            List<NotificationRequest.NotificationRequestItem> items = req.notificationItems;

            if (items != null && !items.isEmpty()) {
                for (NotificationRequest.NotificationRequestItem item : items) {
                    NotificationRequest.Data data = item.data;

                    // Your logic to handle the notification item goes here
                    System.debug('Received event type: ' + item.eventType);
                    System.debug('Received amount: ' + data.amount);

                    // Create a payment object and insert into the database
                        Payments__c payment = new Payments__c(
                        Amount_Paid__c = data.amount,
                        Country__c = data.country,
                        Currency__c = data.currency_z,
                        Customer_Email__c = data.email,
                        Customer_Name__c = data.fullName,
                        Payment_Date__c =Datetime.valueOfGmt(item.eventDate.substring(0, 10) + ' ' + item.eventDate.substring(11, 19)),
                        Payment_Reference__c = data.reference,
                        Payment_Status__c = data.reason,
                        Reason__c = data.reason
                    );
                    System.debug('1. Payment: ' + payment);

                    // Lookup relationship with Virtual_Account__c
                    payment.Virtual_Account__c = getVirtualAccountLookupId(data.creditAccountNumber);
                    System.debug('2. Payment: ' + payment);
                      
                    // Insert payment record
                    insert payment;

                    // Insert into Salesforce object (Assuming you have a custom object named VANotification__c)
                    VA_Notificaton__c notification = new VA_Notificaton__c(
                        Event_Type__c = item.eventType,
                        Event_Date__c = Datetime.valueOfGmt(item.eventDate.substring(0, 10) + ' ' + item.eventDate.substring(11, 19)),
                        Event_Id__c = item.eventId,
                        Amount__c = data.amount,
                        Country__c = data.country,
                        Credit_Account_Number__c = data.creditAccountNumber,
                        Credit_Account_Name__c = data.creditAccountName,
                        Currency__c = data.currency_z,
                        Email__c = data.email,
                        External_Reference__c = data.externalReference,
                        Name = data.fullname,
                        Gateway_Code__c = data.gatewayCode,
                        Code__c = data.code,
                        InternalRef__c = data.internalRef,
                        Gateway_Message__c = data.gatewayMessage,
                        Mobile__c = data.mobile,
                        Narration__c = data.narration,
                        Origin__c = data.origin,
                        Originator_Account_Number__c = data.originatorAccountnumber,
                        Originator_Name__c = data.originatorName,
                        Public_Key__c = data.publicKey,
                        Reference__c = data.reference,
                        Reason__c = data.reason
                    );
                      System.debug('item.eventDate: ' + item.eventDate);

                    // Insert notification record
                    insert notification;
                }
            }
            System.debug('Success');
            return 'Success';
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            return 'Error: ' + e.getMessage();
        }
    }

    private static Id getVirtualAccountLookupId(String accountNumber) {
        try {
            Virtual_Account__c virtualAccount = [SELECT Id FROM Virtual_Account__c WHERE AccountNumber__c = :accountNumber LIMIT 1];
            return virtualAccount != null ? virtualAccount.Id : null;
        } catch (Exception e) {
            System.debug('Error in getVirtualAccountLookupId: ' + e.getMessage());
            return null;
        }
    }
}